### ISSUE TITLE
Blob serializer type

### ISSUE THREAD

**Issue by AndreyMashukov** [AndreyMashukov/mysql-json-serializer#48]
* It should allow to convert blob to RAW data use CONVERT function 

example: 
```sql
SELECT JSON_OBJECT('id',pge_id, 'body', CONVERT(pge_body USING utf8)) FROM page WHERE pge_id = 27
```
Create `BlobType` it should allows to return something like this:
```php
return "CONVERT({$column} USING utf8)";
```

**Comment by Compolomus** [comment]
Сам себе задачи нарезаешь?

**Comment by AndreyMashukov** [comment]
@Compolomus Да. Удобно и не забуду потом как это запилить.
